'use client';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';

const ROLES = [
  {
    id: 'INVESTOR',
    icon: '📊',
    title: 'Investor',
    desc: 'Browse tokenised assets, place buy/sell orders, vote on governance proposals, and claim quarterly distributions.',
    features: ['Access to all listed assets', 'Real-time order book trading', 'USDC distributions to wallet', 'Governance voting rights'],
    color: '#1A3C5E'
  },
  {
    id: 'ISSUER',
    icon: '🏢',
    title: 'Issuer',
    desc: 'List a tokenised asset on the platform. Raise capital, manage distributions, and engage with your investor base.',
    features: ['Submit assets for listing', 'Quarterly financial reporting', 'Manage investor communications', 'Create governance proposals'],
    color: '#C8972B'
  },
  {
    id: 'PARTNER',
    icon: '🤝',
    title: 'Partner / Introducer',
    desc: 'Refer investors and issuers to the platform and earn recurring commission on all fees generated by your clients.',
    features: ['Unique referral link', '20-25% trading fee commission', 'Full pipeline tracking', 'Monthly USDC commission payouts'],
    color: '#16A34A'
  }
];

export default function RoleSelectPage() {
  const router   = useRouter();
  const [selected, setSelected]   = useState(null);
  const [loading, setLoading]     = useState(false);
  const [user, setUser]           = useState(null);

  useEffect(() => {
    const stored = localStorage.getItem('user');
    if (!stored) return router.push('/signup');
    const u = JSON.parse(stored);
    setUser(u);
    // If role already set beyond default INVESTOR, go to dashboard
    if (u.role && !['INVESTOR'].includes(u.role) && u.onboarding_complete) {
      router.push(`/${u.role.toLowerCase()}`);
    }
  }, []);

  const handleConfirm = async () => {
    if (!selected) return;
    setLoading(true);
    try {
      const token = localStorage.getItem('token');
      const res = await fetch('http://localhost:3001/api/auth/role-select', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` },
        body: JSON.stringify({ role: selected })
      });
      const data = await res.json();
      if (!res.ok) return alert(data.error || 'Failed to set role');
      localStorage.setItem('token', data.token);
      localStorage.setItem('user', JSON.stringify(data.user));
      router.push('/onboarding');
    } catch {
      alert('Network error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#0D1B2A] px-4 py-12">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-10">
          <div className="text-[#C8972B] font-bold tracking-widest text-sm mb-2">STEP 2 OF 3</div>
          <h1 className="text-3xl font-bold text-white">Choose your role</h1>
          <p className="text-gray-400 mt-2 text-sm">
            {user?.full_name ? `Welcome, ${user.full_name.split(' ')[0]}. ` : ''}
            Select how you'll use TokenEquityX. You can always contact us to add additional roles later.
          </p>
        </div>

        {/* Role cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
          {ROLES.map(role => (
            <button
              key={role.id}
              onClick={() => setSelected(role.id)}
              className={`text-left rounded-lg p-6 border-2 transition-all ${
                selected === role.id
                  ? 'border-[#C8972B] bg-[#1A3C5E]'
                  : 'border-[#1A3C5E] bg-[#0D2137] hover:border-[#C8972B]/50'
              }`}
            >
              <div className="flex items-center gap-3 mb-3">
                <div
                  className="w-10 h-10 rounded-full flex items-center justify-center text-xl"
                  style={{ backgroundColor: role.color + '33' }}
                >
                  {role.icon}
                </div>
                <div>
                  <div className="text-white font-bold">{role.title}</div>
                  {selected === role.id && (
                    <div className="text-[#C8972B] text-xs">Selected ✓</div>
                  )}
                </div>
              </div>
              <p className="text-gray-400 text-xs leading-relaxed mb-4">{role.desc}</p>
              <ul className="space-y-1">
                {role.features.map(f => (
                  <li key={f} className="text-gray-300 text-xs flex items-start gap-2">
                    <span className="text-green-400 mt-0.5">✓</span> {f}
                  </li>
                ))}
              </ul>
            </button>
          ))}
        </div>

        {/* Confirm */}
        <div className="flex flex-col items-center gap-3">
          <button
            onClick={handleConfirm}
            disabled={!selected || loading}
            className="bg-[#C8972B] hover:bg-[#b8872b] text-white font-semibold px-10 py-3 rounded text-sm transition disabled:opacity-40"
          >
            {loading ? 'Saving…' : `Continue as ${ROLES.find(r => r.id === selected)?.title || '—'}`}
          </button>
          <p className="text-gray-600 text-xs">You'll complete KYC in the next step</p>
        </div>
      </div>
    </div>
  );
}
